---
- name: Filebeat Playbook
  hosts: webservers
  remote_user: azdmin
  become: true
  tasks:
  - name: Download FileBeat .deb package
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
  - name: Install Filebeat with DPKG
    command: dpkg -i filebeat-7.6.1-amd64.deb
  - name: Copy Filebeat Configs
    copy:
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
  -  name: Enable and configure Filebeat System Modules
     command: filebeat modules enable system
  - name: Setup Filebeat
    command: filebeat setup
    command: service filebeat start
  - name: Start filebeat with SystemD
    systemd:
          name: filebeat
          enabled: yes

- name: Metricbeat Playbook
  hosts: webservers
  remote_user: azdmin
  become: true
  tasks:
  - name: Download Metricbeat .deb package
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
  - name: Install Metricbeat with DPKG
    command: dpkg -i metricbeat-7.6.1-amd64.deb
  - name: Copy Metricbeat configs
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
  - name: Enable and configure Metric docker module
    command: metricbeat modules enable docker
  - name: Setup Metricbeat
    command: metricbeat setup
    command: sudo service metricbeat start
  - name: Start metricbeat
    systemd:
          name: metricbeat
          enabled: yes
root@6c7c6ea6efcc:/etc/ansible/roles# cat metricbeat-playbook.yml
---
- name: Metricbeat Playbook
  hosts: webservers
  remote_user: azdmin
  become: true
  tasks:
  - name: Download Metricbeat .deb package
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
  - name: Install Metricbeat with DPKG
    command: dpkg -i metricbeat-7.6.1-amd64.deb
  - name: Copy Metricbeat configs
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
  - name: Enable and configure Metric docker module
    command: metricbeat modules enable docker
  - name: Setup Metricbeat
    command: metricbeat setup
    command: service metricbeat start
  - name: Start metricbeat
    systemd:
          name: metricbeat
          enabled: yes